import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from "next/font/google"

import { cn } from "@/lib/utils";
import { Header } from "@/components/common/Header";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <head>
        {/* <script async
          src={`https://maps.googleapis.com/maps/api/js?key=${process.env.GMAP_TOKEN}&loading=async`}>
        </script> */}
        <link rel="icon" href="/logo.svg" />
        <title>Amendonnez Bougez</title>
        <meta name="description" content="L’association 'Amendonnez Bougez' propose aux enfants de Blagnac une découverte ludique de multiples sports, en partenariat avec les clubs locaux. Une belle opportunité pour trouver l’activité idéale… et inciter petits et grands à bouger !" />
        <meta name="robots" content="index, follow"/>

      </head>
      <body
        className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable)}
      >
        <Header />
        <div
          id="home"
          className="
            bg-gray-100
            px-3 py-5 md:px-[10%] xl:px-[20%]
            flex flex-col items-center"
        >
          {children}
        </div>
      </body>
    </html>
  );
}
